<?php

/**
 * @file
 * Contains localgov_search.install.
 */

/**
 * Implements hook_install().
 */
function localgov_search_install() {

  // Ensure the sitewide search viewmodes are set on view and index.
  $node_bundles = \Drupal::service('entity_type.bundle.info')->getBundleInfo('node');
  foreach ($node_bundles as $bundle => $info) {
    localgov_search_entity_bundle_create('node', $bundle);
  }
}
