<?php

/**
 * @file
 * Hook functions for bc_localgov_events.
 */

use Drupal\views\ViewExecutable;

/**
 * Implements hook_form_views_exposed_form_alter().
 */
function bc_localgov_events_form_views_exposed_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $view = $form_state->getStorage('view');
  if ($form_id == 'views_exposed_form' && $view['view']->id() == 'localgov_events_listing') {
    $form['pick_a_date'] = [
      '#type' => 'date',
      '#title' => t('Pick a date'),
      '#date_date_element' => 'date',
    ];

  }
}


/**
 * Implements hook_views_query_alter().
 */
function bc_localgov_events_views_pre_view(ViewExecutable $view) {
  if ($view->id() == 'localgov_events_listing') {
    $filters = $view->getExposedInput();
    if (isset($filters['pick_a_date']) && $filters['pick_a_date'] != '') {
      $filters['start'] = $filters['pick_a_date'];
      $filters['end'] = date('Y-m-d', strtotime($filters['pick_a_date'] . ' + 1 days'));
      $filters['dates'] = 'choose';
      $view->setExposedInput($filters);
    }
  }
}
