<?php

use Drupal\views\ViewExecutable;
use Drupal\node\NodeInterface;
use RRule\RRule;
use RRule\RSet;

/**
 * Implements hook_preprocess_node().
 *
 * Prepares data to display on the event page with the current or
 * next occurrence of the event.
 *
 * @param $variables
 * @throws Exception
 */
function bc_localgov_events_preprocess_node(&$variables) {

  // @TODO: WIP

  $node = $variables['node'];

  // @TODO: Add bunch of checks for fields and RRule.

  $rrule_string = $node->get('localgov_event_date')->rrule;
  $date_start = $node->get('localgov_event_date')->value;
  $date_end = $node->get('localgov_event_date')->end_value;
  $rrule = new RRule($rrule_string, $date_start);
  $rrule_occurrences = $rrule->getOccurrences();
  $last_occurrence = end($rrule_occurrences);
  $last_occurrence_date = $last_occurrence->format('Y-m-d');
  $today = date('Y-m-d');
  $occurring_today = $rrule->occursAt($today);
  $calculated_occurrences = $rrule->count();
  $future_occurrences = $rrule->getOccurrencesBetween($today, $last_occurrence_date);

  $content_types = [
    'localgov_event',
  ];

}

/**
 * Implements hook_views_pre_render().
 *
 * Aggregates multi-day events into one result.
 *
 * @param ViewExecutable $view
 * @throws Exception
 */
function localgov_events_views_pre_render(ViewExecutable $view) {
  // Only run on a specific view for now.
  if ($view->id() === 'localgov_events_listing') {
    // Save original results to loop through them.
    $original_results = $view->result;
    // Create array for storing unique events.
    $unique_events = [];
    // Temporary index to fix order later.
    $index = -1;
    foreach ($original_results as $result) {
      // Get the node ID for comparing how many unique events are.
      $nid = $result->nid;
      // Save both start and end date to change how they display on the results page.
      $start_date = $result->date_recur__node__localgov_event_date_node_field_data_localg;
      $end_date = $result->date_recur__node__localgov_event_date_node_field_data_localg_1;
      // If a unique event doesn't exist already, add it.
      if (!array_key_exists($result->nid, $unique_events)) {
        $unique_events[$result->nid] = $result;
      }
      // If the current element (event) of the loop already exists within the unique events,
      // compare the date to see if the end date is further in the future than the current
      // saved one, if the case, update that to have the future end date.
      else {
        $old_end_date = new DateTime($unique_events[$nid]->date_recur__node__localgov_event_date_node_field_data_localg_1);
        $new_end_date = new DateTime($end_date);
        if ($new_end_date > $old_end_date) {
          $unique_events[$nid]->date_recur__node__localgov_event_date_node_field_data_localg_1 = $end_date;
        }
      }
    }
    // Fix index elements to correctly display all events.
    $final_results = [];
    foreach ($unique_events as $unique_event){
      ++$index;
      $unique_event->index = $index;
      array_push($final_results, $unique_event);
    }
    // Set the modified results into the views' result.
    $view->result = $final_results;
    $view->total_rows = (string) count($final_results);
  }
}
